version: "2"
services:
    lb:
        image: dockercloud/haproxy:1.6.2
        links:
            - registry
            - registry-ui
        ports:
            - "80:80"
            - "443:443"
            - "5000:5000"
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    
    registry:
        image: registry:2
        restart: always
        expose:
            - 5000
        environment:
            TCP_PORTS: "5000"
            VIRTUAL_HOST: "*:5000, https://*:5000"
            FORCE_SSL: "true"
            REGISTRY_STORAGE_DELETE_ENABLED: "true"
    
    registry-ui:
        image: konradkleine/docker-registry-frontend:v2
        restart: always
        environment:
            VIRTUAL_HOST: "*, https://*"
            ENV_DOCKER_REGISTRY_HOST: "registry"
            ENV_DOCKER_REGISTRY_PORT: 5000
        links:
            - registry
        expose:
            - 80

